######################################################################
# Automatically generated by qmake (3.0) Tue Feb 9 19:46:30 2016
######################################################################

TEMPLATE = app
TARGET = tests
INCLUDEPATH += .

# Input
HEADERS += catch.hpp
SOURCES += accountmanagertest.cpp matchtest.cpp
