######################################################################
# Automatically generated by qmake (3.0) Tue Feb 9 21:29:10 2016
######################################################################

TEMPLATE = app
TARGET = tests
INCLUDEPATH += .

# Input
HEADERS += catch.hpp ../src/accountmanager.h
SOURCES += accountmanagertest.cpp matchtest.cpp ../src/accountmanager.cpp
