######################################################################
# Automatically generated by qmake (3.0) Wed Mar 2 22:52:54 2016
######################################################################

TEMPLATE = app
TARGET = tests
INCLUDEPATH += .

CONFIG += c++11

LIBS += -ldl

# Input
HEADERS += catch.hpp ../src/accountmanager.h ../src/json/json.h ../src/json/json.h ../src/json/json-forwards.h \
        ../src/account.h \
        ../src/sqlite/sqlite3.h \
        ../src/sqlite/sqlite.hpp
SOURCES += accountmanagertest.cpp \
        matchtest.cpp \
        ../src/accountmanager.cpp \
        ../src/jsoncpp.cpp \
        accounttest.cpp \
        ../src/account.cpp \
        ../src/sqlite/sqlite3.c \
        ../src/sqlite/sqlite.cpp
